parameters:
    # explicit environment of analyzed application
    kernel_environment: ''
    # explicit  kernel class of analyzed application
    kernel_class: ''

services:
    _defaults:
        public: true
        autowire: true

    Rector\Symfony\:
        resource: '../src'
        exclude:
            - '../src/Rector/**/*Rector.php'
            - '../src/PhpDocParser/Ast/PhpDoc/*'
